Re-former project
NataJenkins/re-former- pull request #1
Opened 2020-12-03 22:42 UTC by NataJenkins

In this project we created a simple form using
-assosiations
-controllers
-data structures and relationships

2020-12-03 23:55 UTC, lekegitrepo requested changes
## Status: Changes Required :recycle:
#### Hi @NataJenkins and @elberthcorniell :clap: :clap:
#### The project function as expected and kudos :+1: to you for adding validations to check user inputs. However, some requirements are not implemented. Check my comments below :point_down:

#### View:
- **_new.html.erb_**
###### commented out `form`
* [ ] **_it uses `users_path` helper for action_**
* [ ] **_it uses `post` for method_**
* [ ] **_it uses `"UTF-8"` for ccept-charset_**
* [ ] **_it uses `user[<field_name>]` for input's name_**
* [ ] **_it uses form_authenticity_token_**

###### commented out `form_tag`
* [ ] **_it uses `label_tag`, `text_field_tag`, `email_field_tag`, `password_field_tag`_**

#### Optional:
- **_You can create partial for user form and reused in edit and new view_**

- **_Add validation to format email by using either a regular expression or a built-in URI method._**

#### _Reviewed  by Temitayo Adeleke_

2020-12-03 23:55 UTC, lekegitrepo commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
- **_Remove commented  code_**

2020-12-03 23:55 UTC, lekegitrepo commented on app/controllers/users_controller.rb
> +  end
- **_This method should be private since it is only used within the user controller class._**
```
private

def user_params
```

2020-12-03 23:55 UTC, lekegitrepo commented on README.md
> +-Now your environment is ready to run the project. Type rails server
**_[Optional] Try to format the setup instructions. I think you need to put space between the hyphen(-) at the beginning of each line and the sentences_**

2020-12-04 22:17 UTC, Dandush03 approved these changes
# Status: Approved! :rocket: 
### Great work implementing the necessary changes!
# Happy Coding! :tophat: :nerd_face:

2020-12-04 22:17 UTC, merged